###
GET https://localhost:3000/api/hello

###
GET https://localhost:3000/api/lobby

###
POST https://localhost:3000/api/lobby
content-type: application/json

{

}

###
DELETE https://localhost:3000/api/lobby
content-type: application/json

{
	"userId":"57c6f104-b66c-475a-acbe-d910db978b37"
}

###
GET	https://localhost:3000/api/user?userId=79b8f448-cb2f-4ad3-b4c5-690f7075ff29

###
POST https://localhost:3000/api/lobby
content-type: application/json

{
	"pseudo":"john",
}

###
POST https://localhost:3000/api/lobby
content-type: application/json

{
	"pseudo":"alice",
}

###
GET https://localhost:3000/api/ws
id:"2cf5e66c-f990-4af9-a945-7594818ca674"
